### PR TITLE
Backport v1.11.0

### PR DESCRIPTION
**Pull request by Eric-Warehime**
Merge changes up to upstream v1.11.0  
I've tried to maintain functionality where possible--the main changes being:
*  https://github.com/deepmap/oapi-codegen/commit/92ed2364059555d07b1e484c29aefce8044c3b25
* https://github.com/deepmap/oapi-codegen/commit/9cd29e22fd2f9b48236718bc7c53b4d7a91a4c02

I made a small change to the way `-type-mappings` are specified. The old format `integer=uint64` is now `integer:uint64` to follow the package's method for how maps are specified via the CLI.

I did end up removing https://github.com/deepmap/oapi-codegen/commit/9cd29e22fd2f9b48236718bc7c53b4d7a91a4c02 since it caused a bunch of test errors and it seems like they are raising the same error when the query params don't match.

### CODE REVIEW

**Comment by Eric-Warehime** [comment]
I've run this new version of oapi-codegen against the current algod API spec, and committed the changes in the generated code to https://github.com/algorand/go-algorand/compare/master...Eric-Warehime:go-algorand:oapi-v1.11.0-backport-changes so that people can review what the actual changes to our API would be from running this new generator code.

**Comment by Eric-Warehime** [comment]
I've been looking at the diff to make sure this won't functionally break us and I found something weird:

The version 2 spec for certain responses (GET /v2/participation "GetParticipationKeys" for example) returns a ref to a response type (`ParticipationKeysResponse` is an object containing an array of `ParticipationKey` objects). The version 3 spec (which is what we generated our code from) instead has an inline object in the response. 

This new version of the generator is not generating unused objects so these are deleted in the diff I posted above whereas the old version is generating all types regardless.

v2 GetParticipationKeys: https://github.com/algorand/go-algorand/blob/master/daemon/algod/api/algod.oas2.json#L712  
v3 GetParticipationKeys: https://github.com/algorand/go-algorand/blob/master/daemon/algod/api/algod.oas3.yml#L3269

I'm going to further look into the differences between the specs and whether the change we need to make is in how the v3 spec is generated or by telling the generator to create all types regardless of them being unused.

**Comment by Eric-Warehime** [comment]
I reran code generation with `skip-prune` enabled on the output options which looks to have fixed the deletion of "unused" types that was showing up.

**Comment by Eric-Warehime** [comment]
I've made a small change to how response types are generated in order to fix a bug (it looks like a bug anyways) with how enums are not being generated when they are embedded in response types. You can see the change this causes in our generated code in this commit https://github.com/algorand/go-algorand/commit/337bf9e48f1d05456417474838965982345f01bc

**Comment by winder** [comment]
I think the results speak for themself. LGTM.

**Review by winder — APPROVED** [review]

**Pull request merged**
